# Computations with numpy

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
print(values)
print(compute_reciprocals(values))

[6 1 4 4 8]
[0.16666667 1.         0.25       0.25       0.125     ]


In [2]:
1/values

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array = np.random.randint(1, 100, 1000000)
%timeit compute_reciprocals(big_array)

2.89 s ± 89.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit 1/big_array

4.86 ms ± 46.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
x = np.arange(5)
y = np.arange(1,6)

print(x)
print(y)
print(x/y)

[0 1 2 3 4]
[1 2 3 4 5]
[0.         0.5        0.66666667 0.75       0.8       ]


### Agreggates

In [8]:
x = np.arange(1, 10)
print(x)
print(np.add.reduce(x)) # soma os elementos do ndarray

[1 2 3 4 5 6 7 8 9]
45


In [9]:
np.multiply.reduce(x) # multiplica todos os elementos do ndarray, um a um

362880

In [12]:
np.add.accumulate(x) # soma, acumulando

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [13]:
np.multiply.accumulate(x) # multiplica cada elemento, acumulando.

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [18]:
x = np.arange(1,5) # valores de 1 a 4
y = np.arange(5,9) # valores de 5 a 8

In [15]:
x

array([1, 2, 3, 4])

In [17]:
y

array([5, 6, 7, 8])

In [16]:
np.multiply.outer(x,y)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [23]:
a = np.arange(2,5) # valores de 2 a 3
a

array([2, 3, 4])

In [21]:
b = np.arange(0,7) # valores de 0 a 6
b

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
np.multiply.outer(a, b)

array([[ 0,  2,  4,  6,  8, 10, 12],
       [ 0,  3,  6,  9, 12, 15, 18],
       [ 0,  4,  8, 12, 16, 20, 24]])

In [25]:
np.multiply.outer(b,a)

array([[ 0,  0,  0],
       [ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16],
       [10, 15, 20],
       [12, 18, 24]])

In [26]:
L = np.random.random(100)

In [27]:
np.add.reduce(L)

50.46175845319564

In [28]:
np.sum(L)

50.46175845319564

In [29]:
big_array = np.random.randint(1, 100, 1000000)
%timeit np.sum(big_array)
%timeit sum(big_array)

395 µs ± 3.69 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
78.9 ms ± 2.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
np.min(L)

0.017651866638478286

In [31]:
np.max(L)

0.9966328433976568

In [32]:
%timeit min(big_array)
%timeit np.min(big_array)

68.6 ms ± 2.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
252 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Multi-dimensional agregates

In [33]:
M = np.random.randint(0,9, (3,4)) # valores de 0 a 9, 3 linhas e 4 colunas
M

array([[5, 4, 3, 0],
       [4, 5, 2, 2],
       [4, 1, 7, 5]])

In [34]:
M.sum()

42

In [35]:
M.sum(axis=0) # eixo das colunas

array([13, 10, 12,  7])

In [36]:
M.sum(axis=1) # eixo das linhas

array([12, 13, 17])

In [39]:
M.mean(axis=0) # eixo das colunas

array([4.33333333, 3.33333333, 4.        , 2.33333333])

In [41]:
M.mean() # eixo das linhas (default)

3.5

### Logical Operations

In [43]:
x = np.array([1,2,3,4,5])

In [44]:
x < 3

array([ True,  True, False, False, False])

In [45]:
x > 3

array([False, False, False,  True,  True])

In [46]:
x >= 3

array([False, False,  True,  True,  True])

In [47]:
x != 3

array([ True,  True, False,  True,  True])

In [48]:
x == 3

array([False, False,  True, False, False])

In [49]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [50]:
x ^ 2

array([3, 0, 1, 6, 7], dtype=int32)

In [51]:
x

array([1, 2, 3, 4, 5])

In [52]:
x ** 2

array([ 1,  4,  9, 16, 25])

In [56]:
rng = np.random
X = rng.randint(10, size=(3,4))
X

array([[7, 0, 4, 2],
       [5, 9, 8, 6],
       [3, 8, 7, 0]])

In [57]:
X < 6

array([[False,  True,  True,  True],
       [ True, False, False, False],
       [ True, False, False,  True]])

In [58]:
np.count_nonzero(X < 6)

6

In [59]:
np.any(X < 6)

True

In [60]:
np.any(X > 9)

False

In [61]:
np.all(X < 6)

False

### Booleans operataions

In [63]:
x = rng.randint(20, size=(1,10))
x

array([[ 1,  4, 19,  4, 13, 13, 15, 14,  9,  3]])

In [64]:
(x > 4) & (x <= 10)

array([[False, False, False, False, False, False, False, False,  True,
        False]])

In [65]:
np.sum((x < 4) | (x > 10))

7

### Fancy Indexing

In [66]:
x = rng.randint(100, size=(10))
x

array([64, 79, 37, 74, 51, 53, 37, 28, 83, 63])

In [68]:
x[[2,4,5]] # busco pelos índices, na ordem que eu quiser!

array([37, 51, 53])

In [69]:
x[x > 30]

array([64, 79, 37, 74, 51, 53, 37, 83, 63])

In [70]:
(x > 30) & (x < 60)

array([False, False,  True, False,  True,  True,  True, False, False,
       False])

In [71]:
(x % 2) == 0

array([ True, False, False,  True, False, False, False,  True, False,
       False])

In [72]:
x

array([64, 79, 37, 74, 51, 53, 37, 28, 83, 63])

In [73]:
x[(x%2) == 0]

array([64, 74, 28])

In [74]:
np.sum(x[(x%2) == 0])

166

In [75]:
x.size

10

In [76]:
idx = np.arange(x.size)
idx

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x

array([64, 79, 37, 74, 51, 53, 37, 28, 83, 63])

In [78]:
idx[(x%2) == 0]

array([0, 3, 7])

In [79]:
pares = idx[(x%2) == 0]
pares

array([0, 3, 7])

In [80]:
x[pares]

array([64, 74, 28])

In [81]:
X = rng.randint(10, size=(3,4))
X

array([[4, 7, 7, 7],
       [5, 5, 4, 8],
       [1, 4, 8, 0]])

In [82]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(X[0,2])
print(X[1,1])
print(X[2,3])
print(X[row, col])

7
5
0
[7 5 0]
